name: GameboyConnector
version: 1.3.2
main: com.gameboy.connector.GameboyConnector
api-version: 1.20
author: GameBoy.kr
description: GameBoy.kr 웹서버와 통신하는 마인크래프트 플러그인
website: https://gameboy.kr

commands:
  gameboy:
    description: GameBoy Connector 관리 명령어
    usage: /<command> [reload|info|test]
    permission: gameboy.admin
    permission-message: 이 명령어를 사용할 권한이 없습니다.

permissions:
  gameboy.admin:
    description: GameBoy Connector 관리자 권한
    default: op
  gameboy.use:
    description: GameBoy Connector 기본 사용 권한
    default: true